const energyUpgradeData = [
    [
        {
            desc: 'Total Fractal Energy boost AutoBuyers',
            cost: 0,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        }
    ],
    /*
    [
        {
            desc: 'Activating any Color of Pringles boosts Upgrade 0',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Activating Orange Pringles provides extra Drains for Cardinal Upgrade 2',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Activating Yellow Pringles makes the ω6+5 Singularity Function based on Negative Charge Cap',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "Activating any Color of Pringles below the BHO instantly sets your Ordinal to the BHO without emptying that Color",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "Activating Yellow Pringles makes the ω8 Singularity Function Quintuple the Dynamic Cap",
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "Activating Red Pringles now provides free levels of the Third Darkness Upgrade equal to the level of the last Purification Upgrade",
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "Activating any Color of Pringles now fills all other Colors to 50%",
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
    ],
    [
        {
            desc: 'Pringles boost AutoClickers',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "Pringles boost Dynamic Gain if it's lower than the Cap, and Dynamic Cap if it's at the Cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Pringles boost Incrementy Gain',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Pringles boost Negative Charge Gain',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Pringles boost Cardinal Gain',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
    ],
     */
    [
        {
            desc: 'Total Fractal Energy provides free levels of the first ℵ<sub>0</sub> Upgrade',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Total Fractal Energy boosts the Singularity boost to Baselessness and the 2nd Singularity Effect is now positive',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'ℵ<sub>0</sub> boosts the third ℵ<sub>0</sub> Upgrade',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Total Charge boosts the first Singularity Effect',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Unlock Baseless Charge and Baseless Upgrades',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Total Fractal Energy reduces the third Singularity Effect',
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Unlock a new Singularity Effect',
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
    ],
    [
        {
            desc: 'Toal Fractal Energy boosts the first ℵ<sub>ω</sub> effect',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Total Fractal Energy boosts the ℵ<sub>ω</sub> cap',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Total Fractal Energy boosts the first ℵ<sub>ω</sub> Upgrade',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: "While nothing is being Purified, ℵ<sub>ω</sub> Upgrades three to five provide a combined boost to AutoBuyers",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'While the Obscure are being Purified, Total Fractal Energy boost the FGH Successor',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'While the Infinite are being Purified, Total Fractal Energy divide the Dynamic Factor',
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'While the Eternal are being Purified, total Fractal Energy provides free levels of the fourth ℵ<sub>ω</sub> Upgrade',
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'While the Inferior are being Purified, total Fractal Energy greatly boosts the fifth ℵ<sub>ω</sub> Upgrade',
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
        {
            desc: 'Cardinals provide free ℶ<sub>ω</sub>',
            cost: 3,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: '',
        },
    ],
    [
        {
            desc: "Cardinals slightly boost the first Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: true,
            extraReq: false, //TODO
            extraReqText: ' and unlock Omega Mode',
        },
        {
            desc: "Overcharge slightly boosts the second Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "Charge slightly boosts the third Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "ℵ<sub>0</sub> slightly boosts the fourth Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "Booster Power slightly boosts the fifth Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "Passive Energy slightly boosts the sixth Hyperdynamic Factor's cap",
            cost: 1,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "Dynamic Factor slightly boosts all Hyperdynamic Factor caps",
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
        {
            desc: "Incrementy Boosts AutoClicker speed while in Omega Mode",
            cost: 2,
            effect: () => 1,
            hasExtraReq: false,
            extraReq: true,
            extraReqText: ''
        },
    ],
]